-- MySQL Script generated by MySQL Workbench
-- Tue Dec 30 17:06:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema flytau
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flytau
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flytau` DEFAULT CHARACTER SET utf8 ;
USE `flytau` ;

-- -----------------------------------------------------
-- Table `flytau`.`Airports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`Airports` (
  `Code` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `City` VARCHAR(100) NOT NULL,
  `Country` VARCHAR(100) NOT NULL,
  `Latitude` DECIMAL(9,6) NULL,
  `Longitude` DECIMAL(9,6) NULL,
  PRIMARY KEY (`Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flytau`.`Routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`Routes` (
  `RouteId` INT NOT NULL AUTO_INCREMENT,
  `OriginPort` VARCHAR(10) NOT NULL,
  `DestPort` VARCHAR(10) NOT NULL,
  `DurationMinutes` INT NOT NULL,
  `DistanceKm` INT NULL,
  PRIMARY KEY (`RouteId`),
  UNIQUE INDEX `route_unique` (`OriginPort` ASC, `DestPort` ASC) VISIBLE,
  INDEX `fk_Routes_Origin_idx` (`OriginPort` ASC) VISIBLE,
  INDEX `fk_Routes_Dest_idx` (`DestPort` ASC) VISIBLE,
  CONSTRAINT `fk_Routes_Origin`
    FOREIGN KEY (`OriginPort`)
    REFERENCES `flytau`.`Airports` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Routes_Dest`
    FOREIGN KEY (`DestPort`)
    REFERENCES `flytau`.`Airports` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flytau`.`GuestCustomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`GuestCustomer` (
  `UniqueMail` VARCHAR(45) NOT NULL,
  `PhoneNum` JSON NULL,
  `FirstName` VARCHAR(45) NULL,
  `SecondName` VARCHAR(45) NULL,
  PRIMARY KEY (`UniqueMail`),
  UNIQUE INDEX `UniqueMail_UNIQUE` (`UniqueMail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flytau`.`RegisteredCustomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`RegisteredCustomer` (
  `UniqueMail` VARCHAR(45) NOT NULL,
  `PhoneNum` JSON NULL,
  `FirstName` VARCHAR(45) NULL,
  `SecondName` VARCHAR(45) NULL,
  `Password` VARCHAR(255) NOT NULL,
  `RegistrationDate` DATE NULL,
  `PassportNum` VARCHAR(45) NULL,
  `BirthDate` DATE NULL,
  PRIMARY KEY (`UniqueMail`),
  UNIQUE INDEX `UniqueMail_UNIQUE` (`UniqueMail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flytau`.`Airplanes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`Airplanes` (
  `AirplaneId` VARCHAR(45) NOT NULL,
  `PurchaseDate` DATE NULL,
  `Manufacturer` VARCHAR(45) NULL,
  `CouchRows` INT NULL,
  `CouchCols` INT NULL,
  `BusinessRows` INT NULL,
  `BusinessCols` INT NULL,
  PRIMARY KEY (`AirplaneId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flytau`.`Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`Flights` (
  `FlightId` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NULL,
  `EconomyPrice` DECIMAL(10,2) NULL,
  `BusinessPrice` DECIMAL(10,2) NULL,
  `Duration` INT NULL COMMENT 'Duration in minutes',
  `DepartureDate` DATE NULL,
  `DepartureHour` VARCHAR(45) NULL,
  `OriginPort` VARCHAR(45) NOT NULL,
  `DestPort` VARCHAR(45) NOT NULL,
  `Airplanes_AirplaneId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FlightId`),
  INDEX `fk_Flights_Airplanes1_idx` (`Airplanes_AirplaneId` ASC) VISIBLE,
  CONSTRAINT `fk_Flights_Airplanes1`
    FOREIGN KEY (`Airplanes_AirplaneId`)
    REFERENCES `flytau`.`Airplanes` (`AirplaneId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flytau`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`orders` (
  `UniqueOrderCode` VARCHAR(45) NOT NULL,
  `TotalCost` DECIMAL(10,2) NULL,
  `Status` VARCHAR(45) NULL,
  `GuestCustomer_UniqueMail` VARCHAR(45) NULL,
  `RegisteredCustomer_UniqueMail` VARCHAR(45) NULL,
  `Flights_FlightId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UniqueOrderCode`),
  INDEX `fk_orders_GuestCustomer_idx` (`GuestCustomer_UniqueMail` ASC) VISIBLE,
  INDEX `fk_orders_RegisteredCustomer1_idx` (`RegisteredCustomer_UniqueMail` ASC) VISIBLE,
  INDEX `fk_orders_Flights1_idx` (`Flights_FlightId` ASC) VISIBLE,
  CONSTRAINT `fk_orders_GuestCustomer`
    FOREIGN KEY (`GuestCustomer_UniqueMail`)
    REFERENCES `flytau`.`GuestCustomer` (`UniqueMail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_RegisteredCustomer1`
    FOREIGN KEY (`RegisteredCustomer_UniqueMail`)
    REFERENCES `flytau`.`RegisteredCustomer` (`UniqueMail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_Flights1`
    FOREIGN KEY (`Flights_FlightId`)
    REFERENCES `flytau`.`Flights` (`FlightId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flytau`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`Tickets` (
  `TicketId` INT NOT NULL AUTO_INCREMENT,
  `Class` VARCHAR(45) NULL,
  `RowNum` INT NOT NULL,
  `Seat` VARCHAR(45) NOT NULL,
  `orders_UniqueOrderCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TicketId`),
  INDEX `fk_Tickets_orders1_idx` (`orders_UniqueOrderCode` ASC) VISIBLE,
  CONSTRAINT `fk_Tickets_orders1`
    FOREIGN KEY (`orders_UniqueOrderCode`)
    REFERENCES `flytau`.`orders` (`UniqueOrderCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Note: Seat uniqueness per flight is enforced in the application backend
-- (order_repository.py) rather than via database trigger for better
-- error handling and transaction control.


-- -----------------------------------------------------
-- Table `flytau`.`Managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`Managers` (
  `ManagerId` VARCHAR(45) NOT NULL,
  `PhoneNum` JSON NULL,
  `FirstName` VARCHAR(45) NULL,
  `SecondName` VARCHAR(45) NULL,
  `JoinDate` DATE NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `HouseNum` VARCHAR(45) NULL,
  `Password` VARCHAR(255) NULL,
  PRIMARY KEY (`ManagerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flytau`.`Pilot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`Pilot` (
  `Id` VARCHAR(45) NOT NULL,
  `PhoneNum` JSON NULL,
  `FirstName` VARCHAR(45) NULL,
  `SecondName` VARCHAR(45) NULL,
  `JoinDate` DATE NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `HouseNum` VARCHAR(45) NULL,
  `LongFlightsTraining` TINYINT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flytau`.`Managers_edits_Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`Managers_edits_Flights` (
  `Managers_ManagerId` VARCHAR(45) NOT NULL,
  `Flights_FlightId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Managers_ManagerId`, `Flights_FlightId`),
  INDEX `fk_Managers_has_Flights_Flights1_idx` (`Flights_FlightId` ASC) VISIBLE,
  INDEX `fk_Managers_has_Flights_Managers1_idx` (`Managers_ManagerId` ASC) VISIBLE,
  CONSTRAINT `fk_Managers_has_Flights_Managers1`
    FOREIGN KEY (`Managers_ManagerId`)
    REFERENCES `flytau`.`Managers` (`ManagerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Managers_has_Flights_Flights1`
    FOREIGN KEY (`Flights_FlightId`)
    REFERENCES `flytau`.`Flights` (`FlightId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flytau`.`FlightAttendant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`FlightAttendant` (
  `Id` VARCHAR(45) NOT NULL,
  `PhoneNum` JSON NULL,
  `FirstName` VARCHAR(45) NULL,
  `SecondName` VARCHAR(45) NULL,
  `JoinDate` DATE NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `HouseNum` VARCHAR(45) NULL,
  `LongFlightsTraining` TINYINT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flytau`.`Pilot_has_Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`Pilot_has_Flights` (
  `Pilot_Id` VARCHAR(45) NOT NULL,
  `Flights_FlightId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pilot_Id`, `Flights_FlightId`),
  INDEX `fk_Pilot_has_Flights_Flights1_idx` (`Flights_FlightId` ASC) VISIBLE,
  INDEX `fk_Pilot_has_Flights_Pilot1_idx` (`Pilot_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Pilot_has_Flights_Pilot1`
    FOREIGN KEY (`Pilot_Id`)
    REFERENCES `flytau`.`Pilot` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pilot_has_Flights_Flights1`
    FOREIGN KEY (`Flights_FlightId`)
    REFERENCES `flytau`.`Flights` (`FlightId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flytau`.`FlightAttendant_has_Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`FlightAttendant_has_Flights` (
  `FlightAttendant_Id` VARCHAR(45) NOT NULL,
  `Flights_FlightId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FlightAttendant_Id`, `Flights_FlightId`),
  INDEX `fk_FlightAttendant_has_Flights_Flights1_idx` (`Flights_FlightId` ASC) VISIBLE,
  INDEX `fk_FlightAttendant_has_Flights_FlightAttendant1_idx` (`FlightAttendant_Id` ASC) VISIBLE,
  CONSTRAINT `fk_FlightAttendant_has_Flights_FlightAttendant1`
    FOREIGN KEY (`FlightAttendant_Id`)
    REFERENCES `flytau`.`FlightAttendant` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FlightAttendant_has_Flights_Flights1`
    FOREIGN KEY (`Flights_FlightId`)
    REFERENCES `flytau`.`Flights` (`FlightId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;