-- MySQL Script generated by MySQL Workbench
-- Tue Dec 30 17:06:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`GuestCustomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GuestCustomer` (
  `UniqueMail` VARCHAR(45) NOT NULL,
  `PhoneNum` JSON NULL,
  `FirstName` VARCHAR(45) NULL,
  `SecondName` VARCHAR(45) NULL,
  PRIMARY KEY (`UniqueMail`),
  UNIQUE INDEX `UniqueMail_UNIQUE` (`UniqueMail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RegisteredCustomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RegisteredCustomer` (
  `UniqueMail` VARCHAR(45) NOT NULL,
  `PhoneNum` JSON NULL,
  `FirstName` VARCHAR(45) NULL,
  `SecondName` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NOT NULL,
  `RegistrationDate` DATE NULL,
  `PassportNum` VARCHAR(45) NULL,
  `BirthDate` DATE NULL,
  PRIMARY KEY (`UniqueMail`),
  UNIQUE INDEX `UniqueMail_UNIQUE` (`UniqueMail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airplanes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airplanes` (
  `AirplaneId` VARCHAR(45) NOT NULL,
  `PurchaseDate` DATE NULL,
  `Manufacturer` VARCHAR(45) NULL,
  `Couch (Rows, Cols)` VARCHAR(45) NULL,
  `Business (Rows, Cols)` VARCHAR(45) NULL,
  PRIMARY KEY (`AirplaneId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flights` (
  `FlightId` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NULL,
  `EconomyPrice` FLOAT NULL,
  `BusinessPrice` FLOAT NULL,
  `Duration` VARCHAR(45) GENERATED ALWAYS AS (),
  `DepartureDate` DATE NULL,
  `DepartureHour` VARCHAR(45) NULL,
  `OriginPort` VARCHAR(45) NOT NULL,
  `DestPort` VARCHAR(45) NOT NULL,
  `Airplanes_AirplaneId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FlightId`, `Airplanes_AirplaneId`),
  INDEX `fk_Flights_Airplanes1_idx` (`Airplanes_AirplaneId` ASC) VISIBLE,
  CONSTRAINT `fk_Flights_Airplanes1`
    FOREIGN KEY (`Airplanes_AirplaneId`)
    REFERENCES `mydb`.`Airplanes` (`AirplaneId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `UniqueOrderCode` VARCHAR(45) NOT NULL,
  `TotalCost` VARCHAR(45) GENERATED ALWAYS AS (),
  `Class` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `GuestCustomer_UniqueMail` VARCHAR(45) NOT NULL,
  `RegisteredCustomer_UniqueMail` VARCHAR(45) NOT NULL,
  `Flights_FlightId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UniqueOrderCode`, `GuestCustomer_UniqueMail`, `RegisteredCustomer_UniqueMail`, `Flights_FlightId`),
  INDEX `fk_orders_GuestCustomer_idx` (`GuestCustomer_UniqueMail` ASC) VISIBLE,
  INDEX `fk_orders_RegisteredCustomer1_idx` (`RegisteredCustomer_UniqueMail` ASC) VISIBLE,
  INDEX `fk_orders_Flights1_idx` (`Flights_FlightId` ASC) VISIBLE,
  CONSTRAINT `fk_orders_GuestCustomer`
    FOREIGN KEY (`GuestCustomer_UniqueMail`)
    REFERENCES `mydb`.`GuestCustomer` (`UniqueMail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_RegisteredCustomer1`
    FOREIGN KEY (`RegisteredCustomer_UniqueMail`)
    REFERENCES `mydb`.`RegisteredCustomer` (`UniqueMail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_Flights1`
    FOREIGN KEY (`Flights_FlightId`)
    REFERENCES `mydb`.`Flights` (`FlightId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tickets` (
  `Class` VARCHAR(45) NULL,
  `RowNum` INT NULL,
  `Seat` VARCHAR(45) NULL,
  `orders_UniqueOrderCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`orders_UniqueOrderCode`),
  CONSTRAINT `fk_Tickets_orders1`
    FOREIGN KEY (`orders_UniqueOrderCode`)
    REFERENCES `mydb`.`orders` (`UniqueOrderCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Managers` (
  `ManagerId` VARCHAR(45) NOT NULL,
  `PhoneNum` JSON NULL,
  `FirstName` VARCHAR(45) NULL,
  `SecondName` VARCHAR(45) NULL,
  `JoinDate` DATE NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `HouseNum` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`ManagerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pilot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pilot` (
  `Id` VARCHAR(45) NOT NULL,
  `PhoneNum` JSON NULL,
  `FirstName` VARCHAR(45) NULL,
  `SecondName` VARCHAR(45) NULL,
  `JoinDate` DATE NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `HouseNum` VARCHAR(45) NULL,
  `LongFlightsTraining` TINYINT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Managers_edits_Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Managers_edits_Flights` (
  `Managers_ManagerId` VARCHAR(45) NOT NULL,
  `Flights_FlightId` VARCHAR(45) NOT NULL,
  `Flights_Airplanes_AirplaneId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Managers_ManagerId`, `Flights_FlightId`, `Flights_Airplanes_AirplaneId`),
  INDEX `fk_Managers_has_Flights_Flights1_idx` (`Flights_FlightId` ASC, `Flights_Airplanes_AirplaneId` ASC) VISIBLE,
  INDEX `fk_Managers_has_Flights_Managers1_idx` (`Managers_ManagerId` ASC) VISIBLE,
  CONSTRAINT `fk_Managers_has_Flights_Managers1`
    FOREIGN KEY (`Managers_ManagerId`)
    REFERENCES `mydb`.`Managers` (`ManagerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Managers_has_Flights_Flights1`
    FOREIGN KEY (`Flights_FlightId` , `Flights_Airplanes_AirplaneId`)
    REFERENCES `mydb`.`Flights` (`FlightId` , `Airplanes_AirplaneId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FlightAttendant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FlightAttendant` (
  `Id` VARCHAR(45) NOT NULL,
  `PhoneNum` JSON NULL,
  `FirstName` VARCHAR(45) NULL,
  `SecondName` VARCHAR(45) NULL,
  `JoinDate` DATE NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `HouseNum` VARCHAR(45) NULL,
  `LongFlightsTraining` TINYINT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pilot_has_Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pilot_has_Flights` (
  `Pilot_Id` VARCHAR(45) NOT NULL,
  `Flights_FlightId` VARCHAR(45) NOT NULL,
  `Flights_Airplanes_AirplaneId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pilot_Id`, `Flights_FlightId`, `Flights_Airplanes_AirplaneId`),
  INDEX `fk_Pilot_has_Flights_Flights1_idx` (`Flights_FlightId` ASC, `Flights_Airplanes_AirplaneId` ASC) VISIBLE,
  INDEX `fk_Pilot_has_Flights_Pilot1_idx` (`Pilot_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Pilot_has_Flights_Pilot1`
    FOREIGN KEY (`Pilot_Id`)
    REFERENCES `mydb`.`Pilot` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pilot_has_Flights_Flights1`
    FOREIGN KEY (`Flights_FlightId` , `Flights_Airplanes_AirplaneId`)
    REFERENCES `mydb`.`Flights` (`FlightId` , `Airplanes_AirplaneId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FlightAttendant_has_Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FlightAttendant_has_Flights` (
  `FlightAttendant_Id` VARCHAR(45) NOT NULL,
  `Flights_FlightId` VARCHAR(45) NOT NULL,
  `Flights_Airplanes_AirplaneId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FlightAttendant_Id`, `Flights_FlightId`, `Flights_Airplanes_AirplaneId`),
  INDEX `fk_FlightAttendant_has_Flights_Flights1_idx` (`Flights_FlightId` ASC, `Flights_Airplanes_AirplaneId` ASC) VISIBLE,
  INDEX `fk_FlightAttendant_has_Flights_FlightAttendant1_idx` (`FlightAttendant_Id` ASC) VISIBLE,
  CONSTRAINT `fk_FlightAttendant_has_Flights_FlightAttendant1`
    FOREIGN KEY (`FlightAttendant_Id`)
    REFERENCES `mydb`.`FlightAttendant` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FlightAttendant_has_Flights_Flights1`
    FOREIGN KEY (`Flights_FlightId` , `Flights_Airplanes_AirplaneId`)
    REFERENCES `mydb`.`Flights` (`FlightId` , `Airplanes_AirplaneId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
